### ISSUE TITLE
Blankslate dependency

### ISSUE THREAD

**Issue by voxik** [jimweirich/builder#24]
Hello,

It seems that Blankslate library is far more useful then just for builder and somebody already extracted it into separate gem [1, 2]. Would you consider to remove Blankslate from Builder and use the Blankslate gem as a Builder's dependency? Thank you.

[1] https://rubygems.org/gems/blankslate
[2] https://github.com/masover/blankslate

**Comment by jimweirich** [comment]
BlankSlate is really only useful for Ruby 1.8 code.  Ruby 1.9 should be using the built-in BasicObject.

Although I build blankslate as a separate gem, I don't own the blankslate name on Rubygems.org, so I can't release it there.

**Comment by JackDanger** [comment]
I helped extract Blankslate from Rake because some folks needed it as a single dependency but I in no way want to pretend to be the inventor of it. Jim, I'd be happy to set you up with any credentials needed to push changes to the gem (I'm just not sure how to do that).

Alternatively, I'd be happy to maintain the 1.8 Blankslate gem and pull stuff like this into it, as long as you approve.

**Comment by JackDanger** [comment]
Sorry, I meant "extracted from _Builder_". You're so prolific I got the projects confused :p

**Comment by jimweirich** [comment]
No problem.  I'm not sure how to transfer or share ownership of a gem on RubyGems.  The current builder project will build a blankslate gem separately.  Just grab that, do rake package and push the blankslate gem in pkgs.

**Comment by JackDanger** [comment]
How handy! I'll just push whatever builder gives me.

**Comment by JackDanger** [comment]
I've just pushed blankslate 3.1.2 from the builder project. Thanks for your help, Jim.

**Comment by voxik** [comment]
Thank you guys!
